### ISSUE TITLE
Password for main.zip

### ISSUE THREAD

**Issue by B-Anupam** [akhilrajs/Whatsapp-messaging-BOT#2]
I need to open main.py file however it's encrypted.
Please let me know the password for zip file.

**Comment by akhilrajs** [comment]
im sorry, due to some personal reasons i have encrypted the main.py file. 
im not at liberty to disclose the password .
however you can use the .exe file which is capable of running in all Windows systems

https://github.com/akhilrajs/Whatsapp-messaging-BOT/tree/main/installationfile

**Comment by B-Anupam** [comment]
But exe file isn't working.
The whatsapp web opens but on pressing enter message doesn't get send.
That's why I want to edit py file bro.
Any way of contacting you personally?

**Comment by akhilrajs** [comment]
contact me @ https://wa.me/916282915491?text=Hi%20Akhil%20...

**Comment by akhilrajs** [comment]
> But exe file isn't working. The whatsapp web opens but on pressing enter message doesn't get send. That's why I want to edit py file bro. Any way of contacting you personally?

it might be a simple error did you check the log file ?

**Comment by akhilrajs** [comment]
![2022-12-29_06-21-02](https://user-images.githubusercontent.com/67222042/209890009-ad88f24f-a6f7-4b38-83d5-33a5e38a76d7.gif)
